# /usr/bin/env python3
""""
async_generator from the previous task and new coroutine
called async_comprehension 
"""

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> list[float]:
    """
    This coroutine collects 10 random numbers generated by async_generator and
    returns them as a list.
    """
    result = [i async for i in async_generator()]
    return result
